version: '3.7'
services:
  client:
     image: jjs-client # or docker.pkg.github.com/pavel-the-best/jjs-client/client
     environment:
       JJS_API_URL: http://frontend
#      CERT_FILE: /ssl/fullchain.pem
#      KEY_FILE: /ssl/privkey.pem
#     volume:
#       - /etc/letsencrypt/archive/<domain>/:/ssl
     command:
       /jjs-client
     ports:
       - "443:443"
       - "80:80" # or "80:8080" if DEBUG is set
